config/routes.rb
Rails.application.routes.draw do
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
    validates_presence_of :title
    validates_presence_of :job_type
    validates_presence_of :company_name
    validates_presence_of :occupation
    validates_presence_of :location
    validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :job_type, :occupation, :company_name, :location, :url, :description, :apply_information, :deadline, :created_at, :updated_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   
end

app/helpers/jobs_helper.rb
module JobsHelper
    
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  

  <div class="field">
    <%= f.input :title,label: '工作標題',:input_html => {:style=> 'width: 600px'}%>
    <%= f.label :occupation, '工作時間'%></br>
    <%= f.collection_radio_buttons :occupation, [['full-time', "full-time"] ,['part-time', 'part-time'],['contract', 'contract'],['internship', 'internship'],['other', 'other']], :first, :last,:input_html => {:style=> 'text-align: center'}%></br>
    <%= f.label :job_type, '工作類型' %></br>
    <%= f.collection_radio_buttons :job_type, [['web back-end', 'web back-end'] ,['web front-end', 'web front-end'],['web-design', 'web-design'],['qa/testing', 'qa/testing'],['other', 'other']], :first, :last%></br>
    <%= f.input :company_name,label: '公司名稱',:input_html => {:style=> 'width: 600px'} %>
    <%= f.input :url,label: '公司網站',:input_html => {:style=> 'width: 600px'} %>
    <%= f.input :location,label: '公司地址',:input_html => {:style=> 'width: 600px'} %>
    <%= f.input :description,label: '工作內容',:input_html => {:style=> 'width: 600px'} %>
    <%= f.input :apply_information,label: '備註資訊',:input_html => {:style=> 'width: 600px'} %>
    <%= f.date_select :deadline ,label: '截止日期',control_col: "col-sm-2"%></br></br>
    <%= f.button :submit ,'完成'%></br>
  </div>
  

 

<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job, class:'btn btn-info btn-sm' %> 
<%= link_to 'Back', jobs_path, class:'btn btn-success btn-sm' %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ruby Jobs</h1>

</br>
<table class='table table-hover' cellspacing="0">
  <thead>
    <tr>
      <th>Posted</th>
      <th>Title</th>
      <th>Company name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.created_at %></td>
        <td><%= link_to job.title ,job_path(job) %></td>
        <td><%= job.company_name %></td>
        <td><%= job.location %></td>
        <td><%= link_to '刪除', job, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-warning btn-sm'  %></td>
     </tr>
    <% end %>
  </tbody>
</table>

<br>

<br><%= link_to 'New Job', new_job_path, class:'btn btn-danger btn-sm' %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path,class:'btn btn-success btn-sm' %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show Jobs</h1>



<table class="table table-striped col-md-4 col-md-offset-1">
  <tr>
    <td class="col-xs-6 col-sm-3 "><strong>Title:</strong></td>
    <td><%= @job.title %></td>
  </tr>
   <tr>
    <td><strong>Job type:</strong></td>
    <td><%= @job.job_type %></td>
  </tr>
  <tr>
    <td><strong>Company name:</strong></td>
    <td><%= @job.company_name %></td>
  </tr>
    <tr>
    <td><strong>Company Web:</strong></td>
    <td><%= @job.url %></td>
  </tr>
  <tr>
    <td><strong>Occupation:</strong></td>
    <td><%= @job.occupation %></td>
  </tr>
  <tr>
    <td><strong>Location:</strong></td>
    <td><%= @job.location %></td>
  </tr>
  <tr>
    <td><strong>Description:</strong></td>
    <td><%= @job.description %></td>
  </tr>
  <tr>
    <td><strong>Apply information:</strong></td>
    <td><%= @job.apply_information %></td>
  </tr>
  <tr>
    <td><strong>Deadline:</strong></td>
    <td><%= @job.deadline %></td>
  </tr>
</table>



<%= link_to 'Edit', edit_job_path(@job) ,class:'btn btn-info btn-sm' %> 
<%= link_to 'Back', jobs_path, class:'btn btn-info btn-sm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubyjob</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>